routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');


Auth::routes();

Route::group( ['middleware' => ['auth']], function() {
    Route::get('/dashboard',  'HomeController@dashboard')->name('dashboard');
    
    Route::get('/profile',  'HomeController@profile')->name('profile');
    Route::get('/profile/edit',  'HomeController@profile_edit')->name('profile.edit');
    Route::get('/profile/password',  'HomeController@profile_edit_pw')->name('profile.edit_pw');
    Route::put('/profile/update',  'HomeController@profile_update')->name('profile.update');
    Route::put('/profile/password/update',  'HomeController@profile_pw_update')->name('profile.pw_update');

    Route::get('/analytics',  'AnalyticsController@index')->name('analytics');
    Route::get('/payments',  'PaymentsController@index')->name('payments');
    Route::get('/payments/show',  'PaymentsController@show')->name('payments.show');
    Route::get('/payments/edit',  'PaymentsController@edit')->name('payments.edit');
    Route::get('/payments/selectpayment',  'PaymentsController@selectpayment')->name('payments.selectpayment');
    Route::get('/payments/history',  'PaymentsController@history')->name('payments.history');
    
    
    Route::resource('users', 'UserController');
    Route::get('/users/password/{id}/edit', 'UserController@edit_pw')->name('users.edit_pw');    
    Route::put('/users/password/{id}', 'UserController@update_pw')->name('users.update_pw');    

    Route::resource('roles', 'RoleController');
    Route::resource('posts', 'PostController');
    Route::resource('tags', 'TagController');
    Route::resource('publishers', 'PublisherController');
    Route::resource('books', 'BookController');
    Route::resource('stores', 'StoreController');
    Route::resource('packages', 'PackageController');
    Route::resource('storeInvs', 'Store_InvController');

    Route::get('/stores/{store}/payout',  'StoreController@payout')->name('store.payout');


    //datatables
    Route::any('datatables/getUser', 'DatatablesController@getUser');
    Route::any('datatables/getTag', 'DatatablesController@getTag');
    Route::any('datatables/getPublisher', 'DatatablesController@getPublisher');
    Route::any('datatables/getBook', 'DatatablesController@getBook');
    Route::any('datatables/getStore', 'DatatablesController@getStore');
    Route::any('datatables/getStoreInv/{id}', 'DatatablesController@getStoreInv');
    
    //epubcreator
    Route::resource('creator', 'EpubCreatorController');
    Route::resource('creator.chapter', 'EpubChapterController');
    Route::get('/creator/{draft}/publish', 'EpubCreatorController@publish')->name('creator.publish'); 

    
    //select2
    Route::get('select2/getUser', function(){
        return App\User::whereDoesntHave('publisher', function ($query) {
            $query->where('name','LIKE','%'.request('q').'%')
            ->orWhere('username','LIKE','%'.request('q').'%')                
            ->orWhere('email','LIKE','%'.request('q').'%');
        })->paginate(10);
    });

    Route::get('select2/getBook', function(){
        return App\Publisher::where('name','LIKE','%'.request('q').'%')
            ->paginate(10);
    });

    Route::get('ajax/getBookByID', function(){
        $book= App\Book::find(request('book_id'));

        if(!$book->getMedia('cover')->first())
        $image="http://via.placeholder.com/300x300";
         else
        $image=$book->getMedia('cover')->first()->getUrl();

       // $image =$book->getMedia('cover')->first();
        return Response::json(array("book"=>$book, "image"=>$image));
    });



    Route::get('select2/getNotInStoreBook', function(){
    $store_id = request('store_id');
    $store=App\Store::find($store_id);
    $instoreinv = App\StoreInv::where('store_id', $store_id)->pluck('book_id');
    // $books = App\Book::whereNotIn('id',$instoreinv)->get();
    //$books; exit;
    return App\Book::where('name','LIKE','%'.request('q').'%')->whereNotIn('id',$instoreinv)
            ->paginate(10);
    });

    //upload 
    Route::post('upload/image', 'UploadController@upload_image')->name('upload.image');
});

resources/views/creator/create.blade.php
@extends('layouts.dashboard.master') @section('title', 'Epub Creator') @section('content')

<div class="col-sm-12 bg-white border p-4">

    {{ Form::open(['url' => route('creator.store'), 'files' => 'true']) }}
      
    <div class="form-group">
        {{ Form::label('title', 'Title') }} 
        {{ Form::text('title', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('creator', 'Creator') }} 
        {{ Form::text('creator', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('subject', 'Subject') }} 
        {{ Form::text('subject', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('description', 'Description') }}
         {{ Form::textarea('description', null, array('class' => 'form-control')) }}
    </div>

    <div class="form-group">
        {{ Form::label('publisher', 'Publisher') }} 
        {{ Form::text('publisher', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('contributor', 'Contributor') }} 
        {{ Form::text('contributor', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('published_at', 'Published At') }} 
        {{ Form::date('published_at', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('type', 'Type') }} 
        {{ Form::text('type', null, array('class' => 'form-control', 'required')) }}
    </div>
    
    <div class="form-group">
            {{ Form::label('format', 'Format') }} 
            {{ Form::text('format', null, array('class' => 'form-control', 'required')) }}
        </div>
    
    <div class="form-group">
        {{ Form::label('source', 'Source') }} 
        {{ Form::text('source', null, array('class' => 'form-control', 'required')) }}
    </div>
    
    <div class="form-group">
        {{ Form::label('language', 'Language') }} 
        {{ Form::text('language', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('relation', 'Relation') }} 
        {{ Form::text('relation', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('coverage', 'Coverage') }} 
        {{ Form::text('coverage', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('rights', 'Rights') }} 
        {{ Form::text('rights', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('bookcover', 'Book Cover') }}
        <div class="input-group mb-3">
            <div class="custom-file">
                {{ Form::file('bookCover' ,['class' => "custom-file-input", 'id' => "bookCover", 'accept'=>"image/*", 'required']) }}
                <label class="custom-file-label" for="bookCover">Choose file</label>
            </div>
        </div>
              
        <img id="image_upload_preview" src="http://placehold.it/100x100" class="img-fluid img-thumbnail" alt="your image" />
    </div>


    <a class="btn btn-link" href="{{ route('creator.index') }}">Back</a> 
    {{ Form::submit('Create Draft', array('class' => 'btn btn-primary btn-tools btn-xxx')) }}

    {{ Form::close() }}
</div>
@endsection


@section('js')
@parent
<script>
 function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#image_upload_preview').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#bookCover").change(function () {
        readURL(this);
    });
</script>
@endsection

resources/views/creator/index.blade.php
@extends('layouts.dashboard.master') 
@section('title', 'Ebook Creator')
@section('subtitle', 'All Epubs')

@section('content')

<div class="col-sm-12 mb-2">
    <div class="">
        <div class="d-flex flex-row-reverse">
            <a class="btn btn-success" href="{{ route('creator.create') }}"><i class="fa fa-plus mr-2"></i> Create New Ebook</a>
        </div>
    </div>
</div>

<div class="col-sm-12">
    List of Draft
    <table id="publishers-table" class="table table-bordered table-hover">
        <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Created At</th>
                <th>Action</th>
            </tr>
            @foreach($drafts as $draft)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $draft->title }}</td>
                <td>{{ $draft->created_at }}</td>
                <td>
                    <a class="btn btn-sm btn-success" href="{{ route('creator.show', $draft->id) }}">View</a>
                </td>
            </tr>
            @endforeach
        </thead>
    </table>
</div>

<div class="col-sm-12">
    List of Book Saved
    <table id="publishers-table" class="table table-bordered table-hovered">
        <thead class="thead-dark ">
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Created At</th>
                <th>Action</th>
            </tr>
        </thead>
    </table>
</div>

<div class="col-sm-12">
    List of Preview Book
    <table id="publishers-table" class="table table-bordered table-hovered">
        <thead class="thead-dark ">
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Created At</th>
                <th>Action</th>
            </tr>
        </thead>
    </table>
</div>

@endsection 

resources/views/creator/show.blade.php
@extends('layouts.dashboard.master') 
@section('title', 'Book Management') 
@section('subtitle', '') 
@section('content')

<div class='col-lg-12 bg-white border p-3 '>
    <table class="table table-bordered table-striped">
        <tr>
            <td width="300px" rowspan="15">
                    <div class="card" style="width: 18rem;">
                        @if(!$draft->getMedia('cover')->first())
                        <img class="card-img-top" src="http://via.placeholder.com/300x300">
                        @else

                        <img class="card-img-top" src="{{ $draft->getMedia('cover')->first()->getUrl()}} ">
                        @endif
                    </div>
                    <div class="card-body">
                        @include('shared._upload_image', ['collection' => 'cover', 'model_name' => 'EpubDraft', 'model_id' => $draft->id])

                        <hr />
                        <a class="btn btn-success btn-block" href="{{ route('creator.publish', $draft->id) }}">Publish Book</a>
                        <a class="btn btn-primary btn-block" href="{{ route('creator.chapter.create', $draft->id) }}">Add Chapter</a>
                        <a class="btn btn-danger btn-block">Delete Draft</a>
                        <a class="btn btn-link btn-block" href="{{ route('creator.index') }}">Back</a>
                    </div>
            </td>

            <td>Title</td>
            <td>{{ $draft->title  }}</td>
        </tr>
        <tr>
            <td>Creator</td>
            <td>{{ $draft->creator }}</td>
        </tr>
        <tr>
            <td>Subject</td>
            <td>{{ $draft->subject }}</td>
        </tr>
        <tr>
            <td>Description</td>
            <td>{{ $draft->description }}</td>
        </tr>
        <tr>
            <td>Publisher</td>
            <td>{{ $draft->publisher }}</td>
        </tr>
        <tr>
            <td>Contributor</td>
            <td>{{ $draft->contributor }}</td>
        </tr>
        <tr>
            <td>Contributor</td>
            <td>{{ $draft->contributor }}</td>
        </tr>
        <tr>
            <td>Published At</td>
            <td>{{ $draft->published_at }}</td>
        </tr>
        <tr>
            <td>Type</td>
            <td>{{ $draft->type }}</td>
        </tr>

        <tr>
            <td>Format</td>
            <td>{{ $draft->format }}</td>
        </tr>

        <tr>
            <td>Source</td>
            <td>{{ $draft->source }}</td>
        </tr>

        <tr>
            <td>Language</td>
            <td>{{ $draft->language }}</td>
        </tr>

        <tr>
            <td>Relation</td>
            <td>{{ $draft->relation }}</td>
        </tr>

        <tr>
            <td>Coverage</td>
            <td>{{ $draft->coverage }}</td>
        </tr>

        <tr>
            <td>Rights</td>
            <td>{{ $draft->rights }}</td>
        </tr>
    </table>


    <h3>List of Chapter</h3>
    <ol class="draglist list-group">
        @foreach( $draft->chapters as $chapter )
            <li class="list-group-item">
                {{ $chapter->title }} 
                <a href="{{ route('creator.chapter.show', array($draft->id, $chapter->id)) }}" class="btn btn-sm btn-success float-right">
                    View
                </a>
            </li>
        @endforeach
    </ol>

</div>

@endsection

@section('css')
@parent
<style>
body.dragging, body.dragging * {
  cursor: move !important;
}

.dragged {
  position: absolute;
  opacity: 0.5;
  z-index: 2000;
}

ol.draglist li.placeholder {
  position: relative;
  /** More li styles **/
}
ol.draglist li.placeholder:before {
  position: absolute;
  /** Define arrowhead **/
}
</style>

@endsection

@section('js')
@parent
<script src="{!! asset('js/jquery-sortable.js') !!}"></script>

<script>
    $(function  () {
        $("ol.draglist").sortable();
    });
</script>

@endsection