routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');


Auth::routes();

Route::group( ['middleware' => ['auth']], function() {
    Route::get('/dashboard',  'HomeController@dashboard')->name('dashboard');
    
    Route::get('/profile',  'HomeController@profile')->name('profile');
    Route::get('/profile/edit',  'HomeController@profile_edit')->name('profile.edit');
    Route::get('/profile/password',  'HomeController@profile_edit_pw')->name('profile.edit_pw');
    Route::put('/profile/update',  'HomeController@profile_update')->name('profile.update');
    Route::put('/profile/password/update',  'HomeController@profile_pw_update')->name('profile.pw_update');

    Route::get('/analytics',  'AnalyticsController@index')->name('analytics');
    Route::get('/payments',  'PaymentsController@index')->name('payments');
    Route::get('/payments/show',  'PaymentsController@show')->name('payments.show');
    Route::get('/payments/edit',  'PaymentsController@edit')->name('payments.edit');
    Route::get('/payments/selectpayment',  'PaymentsController@selectpayment')->name('payments.selectpayment');
    Route::get('/payments/history',  'PaymentsController@history')->name('payments.history');
    
    
    Route::resource('users', 'UserController');
    Route::get('/users/password/{id}/edit', 'UserController@edit_pw')->name('users.edit_pw');    
    Route::put('/users/password/{id}', 'UserController@update_pw')->name('users.update_pw');    

    Route::resource('roles', 'RoleController');
    Route::resource('posts', 'PostController');
    Route::resource('tags', 'TagController');
    Route::resource('publishers', 'PublisherController');
    Route::resource('books', 'BookController');
    Route::resource('stores', 'StoreController');
    Route::resource('packages', 'PackageController');
    Route::resource('storeInvs', 'Store_InvController');

    Route::get('/stores/{store}/payout',  'StoreController@payout')->name('store.payout');


    //datatables
    Route::any('datatables/getUser', 'DatatablesController@getUser');
    Route::any('datatables/getTag', 'DatatablesController@getTag');
    Route::any('datatables/getPublisher', 'DatatablesController@getPublisher');
    Route::any('datatables/getBook', 'DatatablesController@getBook');
    Route::any('datatables/getStore', 'DatatablesController@getStore');
    Route::any('datatables/getStoreInv/{id}', 'DatatablesController@getStoreInv');
    
    //epubcreator
    Route::resource('creator', 'EpubCreatorController');
    Route::resource('creator.chapter', 'EpubChapterController');
    Route::get('/creator/{draft}/publish', 'EpubCreatorController@publish')->name('creator.publish'); 

    
    //select2
    Route::get('select2/getUser', function(){
        return App\User::whereDoesntHave('publisher', function ($query) {
            $query->where('name','LIKE','%'.request('q').'%')
            ->orWhere('username','LIKE','%'.request('q').'%')                
            ->orWhere('email','LIKE','%'.request('q').'%');
        })->paginate(10);
    });

    Route::get('select2/getBook', function(){
        return App\Publisher::where('name','LIKE','%'.request('q').'%')
            ->paginate(10);
    });

    Route::get('ajax/getBookByID', function(){
        $book= App\Book::find(request('book_id'));

        if(!$book->getMedia('cover')->first())
        $image="http://via.placeholder.com/300x300";
         else
        $image=$book->getMedia('cover')->first()->getUrl();

       // $image =$book->getMedia('cover')->first();
        return Response::json(array("book"=>$book, "image"=>$image));
    });



    Route::get('select2/getNotInStoreBook', function(){
    $store_id = request('store_id');
    $store=App\Store::find($store_id);
    $instoreinv = App\StoreInv::where('store_id', $store_id)->pluck('book_id');
    // $books = App\Book::whereNotIn('id',$instoreinv)->get();
    //$books; exit;
    return App\Book::where('name','LIKE','%'.request('q').'%')->whereNotIn('id',$instoreinv)
            ->paginate(10);
    });

    //upload 
    Route::post('upload/image', 'UploadController@upload_image')->name('upload.image');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Spatie\Activitylog\Traits\LogsActivity;

use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\HasMedia;

class User extends Authenticatable implements HasMedia
{
    use Notifiable;
    use HasRoles;
    use LogsActivity;
    use HasMediaTrait;

    protected static $logAttributes = ['name', 'email', 'password', 'username']; //disable if dont want allow username as auth
    // protected static $logAttributes = ['name', 'email', 'password'];
    protected static $logOnlyDirty = true;
    protected static $logName = 'users';
    protected static $ignoreChangedAttributes = ['updated_at', 'remember_token'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'username',//disable if dont want allow username as auth
        // 'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function publisher()
    {
        return $this->hasOne(Publisher::class, 'user_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Traits\Authorizable;
use Auth;
use App\User;
use App\Role;
use App\Permission;
use Spatie\Activitylog\Models\Activity;

class UserController extends Controller
{
    use Authorizable;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();
        return view('users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'bail|required|min:2',
            'email' => 'required|email|unique:users',
            'username' => 'required|string|max:20|unique:users', //disable if dont want allow username as auth
            'password' => 'required|confirmed|min:6',
            'roles' => 'required|min:1'
        ]);

        // hash password
        $request->merge(['password' => bcrypt($request->get('password'))]);

        // Create the user
        if ( $user = User::create($request->except('roles', 'permissions')) ) {
            $this->syncPermissions($request, $user);
            flash('User has been created.');
        } else {
            flash()->error('Unable to create user.');
        }

        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        $logs = Activity::where('causer_id', $id)->latest()->limit(100)->get();
        return view('users.show', compact('user', 'logs'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        $roles = Role::all();
        

        return view('users.edit', compact('user', 'roles'));
    }

    public function edit_pw($id)
    {
        $user = User::findOrFail($id);
        return view('users.edit_pw', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'bail|required|min:2',
            'email' => 'required|email|unique:users,email,' . $id,
            'username' => 'required|unique:users,username,' . $id, //disable if dont want allow username as auth
            'roles' => 'required|min:1'
        ]);

        // Get the user
        $user = User::findOrFail($id);

        // Update user
        $user->fill($request->except('roles', 'permissions', 'password'));

        // check for password change
        if($request->get('password')) {
            $user->password = bcrypt($request->get('password'));
        }

        // Handle the user roles
        $this->syncPermissions($request, $user);

        $user->save();
        flash()->success('User has been updated.');
        return redirect()->route('users.show', $id);
    }

    public function update_pw(Request $request, $id)
    {
        $this->validate($request, [
            'password' => 'required|confirmed|min:6',
        ]);

        // Get the user
        $user = User::findOrFail($id);

        // check for password change
        if($request->get('password')) {
            $user->password = bcrypt($request->get('password'));
        }

        $user->save();
        flash()->success('User password has been updated.');
        return redirect()->route('users.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if ( Auth::user()->id == $id ) {
            flash()->warning('Deletion of currently logged in user is not allowed :(')->important();
            return redirect()->back();
        }

        if( User::findOrFail($id)->delete() ) {
            flash()->success('User has been deleted');
        } else {
            flash()->success('User not deleted');
        }

        return redirect()->back();
    }

    private function syncPermissions(Request $request, $user)
    {
        // Get the submitted roles
        $roles = $request->get('roles', []);
        $permissions = $request->get('permissions', []);

        // Get the roles
        $roles = Role::find($roles);

        // check for current role changes
        if( ! $user->hasAllRoles( $roles ) ) {
            // reset all direct permissions for user
            $user->permissions()->sync([]);
        } else {
            // handle permissions
            $user->syncPermissions($permissions);
        }

        $user->syncRoles($roles);
        return $user;
    }
}

resources/views/users/create.blade.php
@extends('layouts.dashboard.master') 
@section('title', 'Create New User') 
@section('subtitle', 'Create') 
@section('content')

<div class="col-lg-12 card p-4">

    {{ Form::open(array('url' => 'users')) }}
    
    <div class="form-group">
        {{ Form::label('email', 'E-Mail Address') }} {{ Form::email('email', null, array('class' => 'form-control', 'required')) }}
    </div>

    {{-- disable if dont want allow username as auth --}}
    <div class="form-group">
        {{ Form::label('username', 'Username') }} {{ Form::text('username', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('name', 'Name') }} {{ Form::text('name', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('password', 'Password') }} {{ Form::password('password', array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('password_confirmation', 'Confirm Password') }} {{ Form::password('password_confirmation', array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('roles_label', 'Roles') }} @foreach($roles as $role)
        <br /> {{ Form::checkbox('roles[]', $role->id) }} {{ Form::label('roles', $role->name) }} @endforeach
    </div>

    {{ Form::submit('Add', array('class' => 'btn btn-success', 'style' => 'width:130px')) }} {{ Form::close() }}

</div>


@endsection

resources/views/users/edit.blade.php
@extends('layouts.dashboard.master')

@section('title', 'User')
@section('subtitle', 'Edit')

@section('content')


    <div class='col-lg-12 bg-white border p-3'>

    {{ Form::model($user, ['route' => ['users.update', $user->id], 'method' => 'PUT']) }}

    <div class="form-group">
        {{ Form::label('name', 'Name') }}
        {{ Form::text('name', null, array('class' => 'form-control', 'required')) }}
    </div>

    {{--  disable if dont want allow username as auth  --}}
    <div class="form-group">
        {{ Form::label('username', 'Username') }}
        {{ Form::text('username', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('email', 'E-Mail Address') }}
        {{ Form::email('email', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('roles_label', 'Roles') }}
        @foreach($roles as $role)
        <br />
        {{ Form::checkbox('roles[]', $role->id) }}
        {{ Form::label('roles', $role->name) }} 
        @endforeach
    </div>

    <a class="btn btn-link" href="{{ url()->previous() }}">Back</a>
    {{ Form::submit('Save', array('class' => 'btn btn-primary btn-tools btn-xxx')) }}

    {{ Form::close() }}

    </div>


@endsection

resources/views/users/edit_pw.blade.php
@extends('layouts.dashboard.master') @section('title', 'User Management') @section('subtitle', 'Edit Password') @section('content')


<div class='col-lg-12 p-4 border bg-white'>
    {{ Form::model($user, ['route' => ['users.update_pw', $user->id], 'method' => 'PUT']) }}

    <div class="form-group">
        {{ Form::label('password', 'Password') }} {{ Form::password('password', array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('password_confirmation', 'Confirm Password') }} {{ Form::password('password_confirmation', array('class' => 'form-control', 'required')) }}
    </div>

    <a class="btn btn-link" href="{{ url()->previous() }}">Back</a> {{ Form::submit('Update', array('class' => 'btn btn-success')) }} {{ Form::close() }}

</div>


@endsection

resources/views/users/index.blade.php
@extends('layouts.dashboard.master') @section('title', 'User') @section('content')
<div class="row no-gutters">
    <div class="col-sm-12 my-3">
        <div class="mb-3">
            <div class="d-flex flex-row-reverse">
                @can('add_users')
                <a href="{{route('users.create')}}" class="btn btn-success">
                    <i class="fas fa-plus mr-2"></i> Add New User
                </a>
                @endcan
            </div>
        </div>
    </div>
    <div class="col-sm-12 card p-4">
        <table id="users-table" class="table table-bordered table-hover">
            <thead class="">
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Roles</th>
                    <th>Created At</th>
                    <th>Action</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

@endsection @section('js') @parent

<script>
    $(function() {
        $('#users-table').DataTable({
            serverSide: true,
            processing: true,
            ajax: '/datatables/getUser',
            columns: [{
                    data: 'DT_Row_Index',
                    orderable: false,
                    searchable: false
                },
                {
                    data: 'name'
                },
                {
                    data: 'email'
                },
                {
                    data: 'roles',
                    name: 'roles.name',
                    orderable: false
                },
                {
                    data: 'created_at'
                },
                {
                    data: 'action',
                    orderable: false,
                    searchable: false
                }
            ]
        });
    });

</script>

@endsection

resources/views/users/show.blade.php
@extends('layouts.dashboard.master') @section('title', 'User Management') @section('subtitle', 'View') @section('content')

<div class='col-lg-12 bg-white border p-3 '>
    <table class="table table-bordered table-striped">
        <tr>
            <td>Name</td>
            <td>{{$user->name}}</td>
        </tr>
        {{-- disable if dont want allow username as auth --}}
        <tr>
            <td>Username</td>
            <td>{{$user->username}}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>{{$user->email}}</td>
        </tr>
        <tr>
            <td>Roles</td>
            <td>
                @foreach($user->roles as$role) {{$role->name}} <br> @endforeach
            </td>
        </tr>
    </table>

    <a class="btn btn-link" href="{{ route('users.index') }}">Back</a>
    <a class="btn btn-info" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">View Activity Log</a> @can('edit_users')
    <a class="btn btn-warning" href="{{route('users.edit', $user->id)}}">Edit</a>
    <a class="btn btn-warning" href="{{route('users.edit_pw', $user->id)}}">Change Password</a> @endcan @can('delete_users')
    <a class="btn btn-xs btn-danger" data-method="delete" data-confirm="confirm" href="{{ route('users.destroy', $user->id) }}">Delete</a> @endcan


</div>

 
<div class="collapse col-lg-12 px-0 py-4" id="collapseExample">
    <div class='col-lg-12 bg-white'>
        <hr />
        <h3 class="my-3">Log Activity</h3>
        <table class="table table-bordered py-3">
            <tr>
                <td>Time</td>
                <td>Model Changes</td>
                <td>Description</td>
                <td>Model ID</td>
            </tr>
            @foreach($logs as $log)
            <tr>
                <td>
                    {{$log->created_at}}
                </td>
                <td>
                    {{$log->subject_type}}
                </td>
                <td>
                    {{$log->description}}
                </td>
                <td>
                    {{$log->subject_id}}
                </td>
            </tr>
            @endforeach
        </table>
    </div>
</div>


@endsection