routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');


Auth::routes();

Route::group( ['middleware' => ['auth']], function() {
    Route::get('/dashboard',  'HomeController@dashboard')->name('dashboard');
    
    Route::get('/profile',  'HomeController@profile')->name('profile');
    Route::get('/profile/edit',  'HomeController@profile_edit')->name('profile.edit');
    Route::get('/profile/password',  'HomeController@profile_edit_pw')->name('profile.edit_pw');
    Route::put('/profile/update',  'HomeController@profile_update')->name('profile.update');
    Route::put('/profile/password/update',  'HomeController@profile_pw_update')->name('profile.pw_update');

    Route::get('/analytics',  'AnalyticsController@index')->name('analytics');
    Route::get('/payments',  'PaymentsController@index')->name('payments');
    Route::get('/payments/show',  'PaymentsController@show')->name('payments.show');
    Route::get('/payments/edit',  'PaymentsController@edit')->name('payments.edit');
    Route::get('/payments/selectpayment',  'PaymentsController@selectpayment')->name('payments.selectpayment');
    Route::get('/payments/history',  'PaymentsController@history')->name('payments.history');
    
    
    Route::resource('users', 'UserController');
    Route::get('/users/password/{id}/edit', 'UserController@edit_pw')->name('users.edit_pw');    
    Route::put('/users/password/{id}', 'UserController@update_pw')->name('users.update_pw');    

    Route::resource('roles', 'RoleController');
    Route::resource('posts', 'PostController');
    Route::resource('tags', 'TagController');
    Route::resource('publishers', 'PublisherController');
    Route::resource('books', 'BookController');
    Route::resource('stores', 'StoreController');
    Route::resource('packages', 'PackageController');
    Route::resource('storeInvs', 'Store_InvController');

    Route::get('/stores/{store}/payout',  'StoreController@payout')->name('store.payout');


    //datatables
    Route::any('datatables/getUser', 'DatatablesController@getUser');
    Route::any('datatables/getTag', 'DatatablesController@getTag');
    Route::any('datatables/getPublisher', 'DatatablesController@getPublisher');
    Route::any('datatables/getBook', 'DatatablesController@getBook');
    Route::any('datatables/getStore', 'DatatablesController@getStore');
    Route::any('datatables/getStoreInv/{id}', 'DatatablesController@getStoreInv');
    
    //epubcreator
    Route::resource('creator', 'EpubCreatorController');
    Route::resource('creator.chapter', 'EpubChapterController');
    Route::get('/creator/{draft}/publish', 'EpubCreatorController@publish')->name('creator.publish'); 

    
    //select2
    Route::get('select2/getUser', function(){
        return App\User::whereDoesntHave('publisher', function ($query) {
            $query->where('name','LIKE','%'.request('q').'%')
            ->orWhere('username','LIKE','%'.request('q').'%')                
            ->orWhere('email','LIKE','%'.request('q').'%');
        })->paginate(10);
    });

    Route::get('select2/getBook', function(){
        return App\Publisher::where('name','LIKE','%'.request('q').'%')
            ->paginate(10);
    });

    Route::get('ajax/getBookByID', function(){
        $book= App\Book::find(request('book_id'));

        if(!$book->getMedia('cover')->first())
        $image="http://via.placeholder.com/300x300";
         else
        $image=$book->getMedia('cover')->first()->getUrl();

       // $image =$book->getMedia('cover')->first();
        return Response::json(array("book"=>$book, "image"=>$image));
    });



    Route::get('select2/getNotInStoreBook', function(){
    $store_id = request('store_id');
    $store=App\Store::find($store_id);
    $instoreinv = App\StoreInv::where('store_id', $store_id)->pluck('book_id');
    // $books = App\Book::whereNotIn('id',$instoreinv)->get();
    //$books; exit;
    return App\Book::where('name','LIKE','%'.request('q').'%')->whereNotIn('id',$instoreinv)
            ->paginate(10);
    });

    //upload 
    Route::post('upload/image', 'UploadController@upload_image')->name('upload.image');
});

app/StoreInv.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class StoreInv extends Model
{
    //
      protected $table='store_invs';

      public function store()
    {
        return $this->belongsTo('App\Store', 'store_id');

    }

    public function item_info()
    {
        return $this->belongsTo('App\Book', 'book_id');
    }

}

app/Http/Controllers/Store_InvController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Store;
use App\StoreInv;
use App\User;
class Store_InvController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('store_invs.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $store_invs = store_invs::all();
        return view('store_invs.create', compact('store_invs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
          $this->validate($request, [
            'price' => 'required',
            'discount' => 'required',
        ]);

        $storeInv = new StoreInv;
        $storeInv->book_id = $request->book_id;
        $storeInv->price = $request->price;
        $storeInv->discount = $request->discount;
        $storeInv->store_id= $request->store_id;
		//suppose to insert publlisher_id if created under publisher


        if ( $storeInv->save() ) {
            flash('Inventory has been registered.');
        } else {
            flash()->error('Unable to register Inventory.');
        }
        return  redirect(url()->previous());
        //return redirect()->route('store_invs.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Store  $store
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    	$store_invs=StoreInv::find($id);
        return view('store_invs.show', compact('store_invs'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Store  $store
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        //Ge
        $store_invs=StoreInv::find($id);
           return view('store_invs.show', compact('store_invs'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Store  $store
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, StoreInv $storeInv)
    {
        //

        $storeInv->price = $request->price;
        $storeInv->discount = $request->discount;
        //suppose to insert publlisher_id if created under publisher
        if ( $storeInv->save() ) {
            flash('Inventory has been updated.');
        } else {
            flash()->error('Unable to update Inventory.');
        }
        return  redirect(url()->previous());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\StoreInv  $storeInv
     * @return \Illuminate\Http\Response
     */
    public function destroy(StoreInv $storeInv)
    {
        if( $storeInv->delete() ) {

            flash()->success('Inventory has been deleted');
        } else {
            flash()->success('Inventory not deleted');
        }
          return  redirect(url()->previous());
        //return redirect()->back();
    }
}

resources/views/store_invs/create.blade.php
@extends('layouts.dashboard.master') @section('title', 'Store Management') @section('subtitle', 'Create') @section('content')

<div class="col-sm-12 bg-white border p-4">
    {{ Form::open(['url' => 'stores', 'files' => 'true']) }}

    <div class="form-group">
        {{ Form::label('name', 'Store Name') }} {{ Form::text('name', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('type_id', '') }}
        <select id="type" name="type" class="select2 form-control" required>
             <option value="General" selected='selected'>General</option>
             <option value="Private">Private</option>
        </select>
    </div>

    <div class="form-group" id="publisher_hid" >
        {{ Form::label('publisher_id', 'Publisher') }}
        <select id="publisher_id" name="publisher_id" class="form-control" required></select>
    </div>

     <div class="form-group">
        {{ Form::label('status', 'Status') }}
        <select id="status" name="status" class="form-control" required>
            <option value="Active" selected='selected'>Active</option>
             <option value="Closed">Closed</option>
        </select>
    </div>

    <br />
    <a class="btn btn-link" href="{{ route('books.index') }}">Back</a> {{ Form::submit('Add', array('class' => 'btn btn-primary btn-tools btn-xxx')) }} {{ Form::close() }}
</div>
@endsection @section('js') @parent
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>



<script>
    $(document).ready(function() {

        $('#type').change(function () {
        var str = this.value;
        if (str=='General')
                $('#publisher_hid').hide();
            else $('#publisher_hid').show();
        }).change();
        

        $('#publisher_id').select2({
            theme: "bootstrap",
            ajax: {
                url: '/select2/getBook',
                dataType: 'json',
                delay: 200,
                data: function(params) {
                    return {
                        q: params.term,
                        page: params.page
                    };
                },
                processResults: function(data, params) {
                    params.page = params.page || 1;
                    return {
                        results: data.data,
                        pagination: {
                            more: (params.page * 10) < data.total
                        }
                    };
                }
            },
            minimumInputLength: 1,
            templateResult: function(repo) {
                if (repo.loading) return repo.name;
                var markup = repo.name;
                return markup;
            },
            templateSelection: function(repo) {
                return repo.name;
            },
            escapeMarkup: function(markup) {
                return markup;
            }
        });

    });

    $('#inputGroupFile01').on('change', function() {
        var fileName = $(this).val();
        $(this).next('.custom-file-label').html(fileName);
    })

    $('#inputGroupFile02').on('change', function() {
        var fileName = $(this).val();
        $(this).next('.custom-file-label').html(fileName);
    })

</script>
@endsection

resources/views/store_invs/index.blade.php
@extends('layouts.dashboard.master') @section('title', 'Store Management') @section('content')

<div class="col-sm-12 mb-4">
    <div class="card">
        <div class="card-body">
            @can('add_stores')
            <a href="{{ route('stores.create') }}" class="btn btn-success">
                    <i class="fas fa-plus"></i> New
                </a> @endcan
        </div>
    </div>

</div>

<div class="col-sm-12">
    <table id="stores-table" class="table table-bordered table-hover">
        <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Type</th>
                <th>Status</th>
                <th>Created At</th>
                <th>Action</th>
            </tr>
        </thead>
    </table>
</div>
@endsection @section('js') @parent

<script>
    $(function() {
        $('#stores-table').DataTable({
            serverSide: true,
            processing: true,
            ajax: {
                url: '/datatables/getStore',
                type: 'post',
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                dataType: 'JSON',
                beforeSend: function(xhr) {
                    xhr.setRequestHeader('Authorization');
                }
            },
            columns: [{
                    data: 'DT_Row_Index',
                    orderable: false,
                    searchable: false
                },
                {
                    data: 'store_name',
                    name: 'stores.name'
                },
                {
                    data: 'type',
                    name: 'stores.type'
                },
                {
                    data: 'status',
                    name: 'stores.status'
                },
                {
                    data: 'created_at',
                    name: 'stores.created_at'
                },
                {
                    data: 'action',
                    orderable: false,
                    searchable: false
                }
            ]
        });
    });

</script>

@endsection

resources/views/store_invs/show.blade.php
@extends('layouts.dashboard.master') @section('title', 'Store Management') @section('subtitle', '') @section('content')

<div class='col-lg-12 bg-white border p-3 '>

    {{ Form::model($store_invs, ['route' => ['storeInvs.update', $store_invs->id], 'method' => 'PUT']) }}
      <div >
        <div >
          <div>
            <h5>Update Inventory</h5>
          </div>
          <div >
            <div class="form-group book_preview">

              <table class="table table-bordered table-striped small">
                <tr>
            <td width="300px" rowspan="4">
                    <div class="card" style="width: 18rem;">
                        @if(!$store_invs->item_info->getMedia('cover')->first())
                        <img class="card-img-top" src="http://via.placeholder.com/300x300">
                        @else

                        <img class="card-img-top" src="{{ $store_invs->item_info->getMedia('cover')->first()->getUrl()}} ">
                        @endif
                    </div>
            </td>

            <td>Name</td>
            <td>{{$store_invs->item_info->name}}</td>
        </tr>
        {{-- disable if dont want allow username as auth --}}
        <tr>
            <td>Author</td>
            <td>{{$store_invs->item_info->author}}</td>
        </tr>
        <tr>
            <td>Epub</td>
            <td><a href="{{ $store_invs->item_info->getMedia('epub')->first()->getUrl()}}">Download</a></td>
            @javascript('epub_url', $store_invs->item_info->getMedia('epub')->first()->getUrl())
        </tr>
        <tr>
            <td>Tags</td>
            <td>
                @foreach($store_invs->item_info->tags as $tag)
                    {{ $tag->name }} @if (!$loop->last) ,@endif
                @endforeach
            </td>
        </tr>
        <tr>
            <td></td>
            <td>Detail</td>
            <td>{{$store_invs->item_info->detail}}</td> 
        </tr>
              </table>
            </div>
            <div class="form-group">
                {{ Form::label('lbl_price', 'Price') }} {{ Form::number('price',$store_invs->price, array('class' => 'form-control', 'required' ,'id' => 'price','step'=>'.01')) }}
            </div>
            <div class="form-group">
                {{ Form::label('lbl_discount', 'Discount (%)') }} {{ Form::number('discount', $store_invs->discount, array('class' => 'form-control', 'required' ,'id' => 'discount','step'=>'.01' )) }}
            </div>
             <div class="form-group">
                {{ Form::label('lbl_total', 'Total Price') }} {{ Form::text('total', '0.00', array('class' => 'form-control', 'readonly' ,'id' => 'total')) }}
            </div>
    <br />
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" onclick="window.location.href='/stores/{{$store_invs->store_id}}'" >Back To Store</button>
            {{ Form::hidden('store_id', $store_invs->store_id,array('id' => 'store_id')) }}
            {{ Form::submit('Update', array('class' => 'btn btn-primary btn-tools btn-xxx')) }}     
          </div>
        </div>
      </div>
    {{ Form::close() }}

            
          

</div>

@endsection

@section('js')
<script src="https://cdn.jsdelivr.net/epub.js/0.2.15/epub.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

<script>
    $(document).ready(function()
  {

     calculateTotal();
     $('#price').keyup(function(){
       calculateTotal();
     });

    $('#discount').keyup(function(){
       calculateTotal();
     });

  });

    function calculateTotal(){
            price= $('#price').val();
            discount =$('#discount').val();
            total =(price-(price*(discount/100))).toFixed(2);
            $('#total').val( total);

    }
   
   
</script>
@endsection